/* tslint:disable */
/* eslint-disable */
//  This file was automatically generated and should not be edited.

export type PaginatedHamamatsuEvents = {
  __typename: "PaginatedHamamatsuEvents",
  items:  Array<HamamatsuEvents >,
  nextToken?: string | null,
};

export type HamamatsuEvents = {
  __typename: "HamamatsuEvents",
  Key: string,
  Code?: string | null,
  No?: string | null,
  Prefecture?: string | null,
  City?: string | null,
  EventName?: string | null,
  EventNameKana?: string | null,
  EventNameEn?: string | null,
  StartedOn?: string | null,
  EndedOn?: string | null,
  StartedAt?: string | null,
  EndedAt?: string | null,
  StartedAtNote?: string | null,
  Description?: string | null,
  Price?: string | null,
  PriceDetail?: string | null,
  Contact?: string | null,
  Tel?: string | null,
  TelExtension?: string | null,
  Organizer?: string | null,
  Place?: string | null,
  PlaceAddress?: string | null,
  Formula?: string | null,
  Latitude?: string | null,
  Longitude?: string | null,
  Access?: string | null,
  Parking?: string | null,
  Capacity?: string | null,
  ClosingOn?: string | null,
  ClosingAt?: string | null,
  HowToJoin?: string | null,
  Url?: string | null,
  Note?: string | null,
  Category?: string | null,
  Distinct?: string | null,
  OpenedAt?: string | null,
  UpdatedAt?: string | null,
  ChildInformation?: string | null,
  FacilityNo?: string | null,
  ImportedAt?: string | null,
  StartMonth?: string | null,
};

export type AllQueryVariables = {
  limit?: number | null,
  nextToken?: string | null,
};

export type AllQuery = {
  all:  {
    __typename: "PaginatedHamamatsuEvents",
    items:  Array< {
      __typename: "HamamatsuEvents",
      Key: string,
      Code?: string | null,
      No?: string | null,
      Prefecture?: string | null,
      City?: string | null,
      EventName?: string | null,
      EventNameKana?: string | null,
      EventNameEn?: string | null,
      StartedOn?: string | null,
      EndedOn?: string | null,
      StartedAt?: string | null,
      EndedAt?: string | null,
      StartedAtNote?: string | null,
      Description?: string | null,
      Price?: string | null,
      PriceDetail?: string | null,
      Contact?: string | null,
      Tel?: string | null,
      TelExtension?: string | null,
      Organizer?: string | null,
      Place?: string | null,
      PlaceAddress?: string | null,
      Formula?: string | null,
      Latitude?: string | null,
      Longitude?: string | null,
      Access?: string | null,
      Parking?: string | null,
      Capacity?: string | null,
      ClosingOn?: string | null,
      ClosingAt?: string | null,
      HowToJoin?: string | null,
      Url?: string | null,
      Note?: string | null,
      Category?: string | null,
      Distinct?: string | null,
      OpenedAt?: string | null,
      UpdatedAt?: string | null,
      ChildInformation?: string | null,
      FacilityNo?: string | null,
      ImportedAt?: string | null,
      StartMonth?: string | null,
    } >,
    nextToken?: string | null,
  },
};

export type QueryByMonthQueryVariables = {
  month: string,
};

export type QueryByMonthQuery = {
  queryByMonth:  {
    __typename: "PaginatedHamamatsuEvents",
    items:  Array< {
      __typename: "HamamatsuEvents",
      Key: string,
      Code?: string | null,
      No?: string | null,
      Prefecture?: string | null,
      City?: string | null,
      EventName?: string | null,
      EventNameKana?: string | null,
      EventNameEn?: string | null,
      StartedOn?: string | null,
      EndedOn?: string | null,
      StartedAt?: string | null,
      EndedAt?: string | null,
      StartedAtNote?: string | null,
      Description?: string | null,
      Price?: string | null,
      PriceDetail?: string | null,
      Contact?: string | null,
      Tel?: string | null,
      TelExtension?: string | null,
      Organizer?: string | null,
      Place?: string | null,
      PlaceAddress?: string | null,
      Formula?: string | null,
      Latitude?: string | null,
      Longitude?: string | null,
      Access?: string | null,
      Parking?: string | null,
      Capacity?: string | null,
      ClosingOn?: string | null,
      ClosingAt?: string | null,
      HowToJoin?: string | null,
      Url?: string | null,
      Note?: string | null,
      Category?: string | null,
      Distinct?: string | null,
      OpenedAt?: string | null,
      UpdatedAt?: string | null,
      ChildInformation?: string | null,
      FacilityNo?: string | null,
      ImportedAt?: string | null,
      StartMonth?: string | null,
    } >,
    nextToken?: string | null,
  },
};

export type GetOneQueryVariables = {
  Key: string,
};

export type GetOneQuery = {
  getOne?:  {
    __typename: "HamamatsuEvents",
    Key: string,
    Code?: string | null,
    No?: string | null,
    Prefecture?: string | null,
    City?: string | null,
    EventName?: string | null,
    EventNameKana?: string | null,
    EventNameEn?: string | null,
    StartedOn?: string | null,
    EndedOn?: string | null,
    StartedAt?: string | null,
    EndedAt?: string | null,
    StartedAtNote?: string | null,
    Description?: string | null,
    Price?: string | null,
    PriceDetail?: string | null,
    Contact?: string | null,
    Tel?: string | null,
    TelExtension?: string | null,
    Organizer?: string | null,
    Place?: string | null,
    PlaceAddress?: string | null,
    Formula?: string | null,
    Latitude?: string | null,
    Longitude?: string | null,
    Access?: string | null,
    Parking?: string | null,
    Capacity?: string | null,
    ClosingOn?: string | null,
    ClosingAt?: string | null,
    HowToJoin?: string | null,
    Url?: string | null,
    Note?: string | null,
    Category?: string | null,
    Distinct?: string | null,
    OpenedAt?: string | null,
    UpdatedAt?: string | null,
    ChildInformation?: string | null,
    FacilityNo?: string | null,
    ImportedAt?: string | null,
    StartMonth?: string | null,
  } | null,
};
